version: "3.8"

services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - db_data:/app/data
    environment:
      - DATABASE_DIR=/app/data
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000

volumes:
  db_data:
    driver: local
